config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your applicaStion routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root 'posts#index'

  resources :posts do
    scope module: :posts do
      resources :comments, only: %i[create]
      resources :likes, only: %i[create destroy]
    end
  end

  resources :users, only: [:show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  MAX_LENGTH_ON_INDEX_PAGE = 255

  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
  belongs_to :category
  belongs_to :creator, class_name: 'User'
  validates :title, length: { in: 5..255 }
  validates :body, length: { in: 100..1000 }

  def cut
    "#{body.slice(0..MAX_LENGTH_ON_INDEX_PAGE)}..."
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :post, counter_cache: :comments_count
  belongs_to :user
  has_ancestry
  validates :content, presence: true
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
  validates :post, uniqueness: { scope: :user }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy, inverse_of: 'creator'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

class Posts::ApplicationController < ApplicationController
  def resource_post
    @resource_post ||= Post.find params[:post_id]
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

class Posts::CommentsController < Posts::ApplicationController
  def create
    @comment = resource_post.comments.build(post_comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to resource_post, notice: t('.success_comment')
    else
      redirect_to resource_post, notice: t('blank_comment')
    end
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:content, :parent_id)
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

class Posts::LikesController < Posts::ApplicationController
  def create
    @like = resource_post.likes.build(user_id: current_user.id)

    if @like.save
      redirect_to resource_post
    else
      redirect_to resource_post, status: :unprocessable_entity
    end
  end

  def destroy
    @post_like = resource_post.likes.find_by(user_id: current_user.id)

    @post_like&.destroy

    redirect_to resource_post
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @posts = Post.order('created_at DESC').includes(:creator)
  end

  def show
    @post = Post.find params[:id]
    @comments_tree = @post.comments.includes(:user).order('created_at DESC').arrange
    @post_user_like = @post.likes.find_by user: current_user
    @comment = PostComment.new
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
    return if current_user.id == @post.creator_id

    redirect_to posts_url, notice: t('.access_error')
    nil
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = Post.find params[:id]

    unless current_user.id == @post.creator_id
      redirect_to posts_url, notice: t('.access_error')
      return
    end

    if @post.update(post_params)
      redirect_to @post, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find params[:id]

    unless current_user.id == @post.creator_id
      redirect_to posts_url, notice: t('.access_error')
      return
    end

    @post.destroy

    redirect_to posts_url, notice: t('.success')
  end

  private

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.includes(:posts).find(params[:id])
    (redirect_to posts_url, notice: t('.access_error')) if current_user.id != @user.id
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsProject64
  meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/navbar'

    = render 'layouts/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              h1 = yield :title

            == yield

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.to_hash.each_value do |msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_navbar.html.slim
.container.mb-2
  .py-2.border-bottom
    .navbar.navbar-expand-md.bg-warning.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4' do
        .h3
          = t('.navbrand')
      ul.nav.nav-pills.flex-grow-1.navbar-nav
        -if user_signed_in?
          li.nav-link.disable.ml-4
            = link_to current_user.email.to_s, user_path(current_user)

          li.nav-item.ml-4
           = link_to new_post_path, class: 'nav-link link-dark'
            = t '.new_post'

          li.nav-item.active.ml-4
            = link_to destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link link-dar' do
             = t '.sign_out'

        -else
          li.nav-item.active.ml-4
            = link_to new_user_session_path, class: 'nav-link link-dark' do
              = t '.sign_in'

          li.nav-item.active.ml-4
            = link_to new_user_registration_path, class: 'nav-link link-dark' do
              = t '.sign_up'

app/views/posts/_post_form.html.slim
= simple_form_for post do |p|
  =p.input :title
  =p.association :category
  =p.input :body
  =p.button :submit, class: 'btn btn-primary'

app/views/posts/comments/_comment.html.slim
.card.border-success.mb-3
  .card-header
    = t('.author', author: comment.user.email, time: l(comment.created_at, format: :long))
  .card-body.text-success
    p.card-text
      = comment[:content]
      - child.each do |comment, child|
        = render partial: 'posts/comments/comment', locals: { new_comment:, child:, comment:, post: }
  .card-footer.bg-transparent.border-success
    - if user_signed_in?
      = link_to "##{comment.id}", data: { 'bs-toggle': 'collapse' }, aria: { controls: comment.id.to_s } do
        =t('.answer')
      .div.collapse [id="#{comment.id}"]
        .div.card.card-body
          = render partial: 'posts/comments/comment_form', locals: { comment: new_comment, post:, parent_id: comment.id }

app/views/posts/comments/_comment_form.html.slim
= simple_form_for comment, method: :post, url: post_comments_path(post) do |c|
  =c.input :content
  =c.hidden_field :parent_id, value: parent_id
  =c.button :submit, class: 'btn btn-warning'

app/views/posts/edit.html.slim
.container
  - content_for :title
    h1.mt-5
      = t('.edit')
  = render partial: 'posts/post_form', locals: { post: @post }

app/views/posts/index.html.slim
.container
  - content_for :title
    h1.mt-5
      = t '.title'
  .row
    - @posts.each do |post|
       .col-md-12
        .card.mb-3
          .card-body
            h5.card-title
              = link_to post.title, post_path(post)
            .card-text.mb2
              = post.cut
            .text-right.small.text-muted.mt-auto
              span.me-2
                = t('.liked', count: post.likes.size)
              span.me-2
                = t('.author', name: post.creator.email)
              span.me-2
                = t('.created', time_ago: (distance_of_time_in_words post.created_at, Time.zone.now))
  -if user_signed_in?
    = link_to new_post_path, class: 'btn btn-primary mt-4' do
      - t('.new_post')

app/views/posts/new.html.slim
.container
  - content_for :title
    h1.mt-5
      = t '.title'
  = render partial: 'posts/post_form', locals: { post: @post }

app/views/posts/show.html.slim
.card.container-fluide
  .card-header
    =link_to root_path do
      = t('.link_to_all_posts')
    = t('.category_name', name: @post.category.name)
  .card-body
    h3
      = @post.title
    .mt-3
    .mb-5 = @post.body
    .card-footer
      .d-flex.justify-content-between
        .d-flex
            .me-5 = t('.author', name: @post.creator.email)
            = t('.created', time_ago: (distance_of_time_in_words @post.created_at, Time.zone.now))
        div
          = t('posts.index.liked', count: @post.likes.count)
          - if user_signed_in?
            - if @post_user_like
              = link_to post_like_path(@post, @post_user_like), data: { turbo_method: :delete } do
                i.bi.bi-arrow-through-heart-fill.h5.ms-2
            - else
              = link_to post_likes_path(@post), data: { turbo_method: :post } do
                i.bi.bi-arrow-through-heart.h5.ms-2
          - else
            i.bi.bi-arrow-through-heart-fill.h5.ms-2.disable

    .card-footer
      - if user_signed_in?
        = render partial: 'posts/comments/comment_form', locals: { comment: @comment, post: @post, parent_id: nil }
        .mb-3
      - @comments_tree.each do |comment, child|
         = render partial: 'posts/comments/comment', locals: { comment:, child:, new_comment: @comment, post: @post }

app/views/users/show.html.slim
.container
  h4
    = t('.page_name')

  h6.mb-3 = t('.author', author: @user.email)

  h6.mb-3 = t('.registred_at', time: l(@user.created_at, format: :long))

  table.table
    thead
      tr
        th[scope='col']
          = t('.table_number')
        th.text-center[scope='col']
          = t('.posts')
        th.text-center[scope='col']
          = t('.comments')
        th.text-center[scope='col']
          = t('.liked')
        th.text-center[scope='col']
          = t('.links_to_work')
    tbody
    - @user.posts.each_with_index do |post, index|
      tr
        th[scope='rows']
          =index + 1
        td
          = post.title
        td.text-center
          = post.comments.size
        td.text-center
          = post.likes.size
        td.text-center
          = link_to edit_post_path(post), class: 'me-3' do
            = t('.edit_post')
          = link_to post_path(post), data: { turbo_method: :delete } do
            = t('.delete_post')